/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  src\xxinverse.c
 *  model: threetank
 *  expmt: threetank
 *  date:  February 4, 2016
 *  time:  4:26:23 PM
 *  user:  INTO-CPS
 *  from:  20-sim 4.6 Professional Single
 *  build: 4.6.1.6733
 **********************************************************/

/* No matrix support functions are needed for this model */

