/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  src\xxmodel.c
 *  model: threetank
 *  expmt: threetank
 *  date:  February 4, 2016
 *  time:  4:26:23 PM
 *  user:  INTO-CPS
 *  from:  20-sim 4.6 Professional Single
 *  build: 4.6.1.6733
 **********************************************************/

/* This file contains the actual model variables and equations */

/* Note: Alias variables are the result of full optimization
   of the model in 20-sim. As a result, only the real variables
   are used in the model for speed. The user may also include
   the alias variables by adding them to the end of the array:

   XXDouble xx_variables[NUMBER_VARIABLES + NUMBER_ALIAS_VARIABLES + 1];
   XXCharacter *xx_variable_names[] = {
     VARIABLE_NAMES, ALIAS_VARIABLE_NAMES, NULL
   };

   and calculate them directly after the output equations:

   void XXCalculateOutput (void)
   {
     OUTPUT_EQUATIONS
     ALIAS_EQUATIONS
   }
*/

/* system include files */
#include <stdlib.h>
#include <math.h>

/* 20-sim include files */
#include "xxmodel.h"
#include "xxfuncs.h"

/* the global variables */
XXDouble xx_start_time = 0.0;
XXDouble xx_finish_time = 20.0;
XXDouble xx_step_size = 0.02;
XXDouble xx_time = 0.0;
XXInteger xx_steps = 0;
XXBoolean xx_initialize = XXTRUE;
XXBoolean xx_major = XXTRUE;
XXBoolean xx_stop_simulation = XXFALSE;

/* the variable arrays */
XXDouble xx_MEMORY[1 + 4 + 2 + 12 + 2 + 2 + 1];
XXDouble* xx_C = xx_MEMORY;		/* constants */
XXDouble* xx_P = xx_MEMORY + 1;			/* parameters */
XXDouble* xx_I = xx_MEMORY + 1 + 4;		/* initial values */
XXDouble* xx_V = xx_MEMORY + 1 + 4 + 2;		/* variables */
XXDouble* xx_s = xx_MEMORY + 1 + 4 + 2 + 12;		/* states */
XXDouble *xx_R = xx_MEMORY + 1 + 4 + 2 + 12 + 2;		/* rates (or new states) */

/* the names of the variables as used in the arrays above
   uncomment this part if these names are needed
XXCharacter *xx_constant_names[] = {
	"pi"
,	NULL
};
XXCharacter *xx_parameter_names[] = {
	"WaterTank3\\Tank3\\area",
	"WaterTank3\\Tank3\\gravity",
	"WaterTank3\\Tank3\\liquid_density",
	"WaterTank3\\Valve\\resistance"
,	NULL
};
XXCharacter *xx_initial_value_names[] = {
	"",
	"WaterTank3\\Tank3\\volume_initial"
,	NULL
};
XXCharacter *xx_variable_names[] = {
	"Drain\\puddle",
	"Time\\output",
	"WaterTank3\\Tank3\\level",
	"WaterTank3\\Tank3\\pipe.e",
	"WaterTank3\\inFlow",
	"WaterTank3\\valveControl",
	"puddle",
	"inFlow",
	"Tank3OutFlow",
	"fmuTime",
	"valveControl",
	"level"
,	NULL
};
XXCharacter *xx_state_names[] = {
	"Drain\\drain_volume",
	"WaterTank3\\Tank3\\volume"
,	NULL
};
XXCharacter *xx_rate_names[] = {
	"Drain\\inFlow",
	"WaterTank3\\Tank3\\volume_dot"
,	NULL
};
*/

/* this method is called before calculation is possible */
void XXModelInitialize (void)
{
	/* set the constants */
	xx_C[0] = 3.14159265358979;		/* pi {} */


	/* set the parameters */
	xx_P[0] = 1.0;		/* WaterTank3\Tank3\area */
	xx_P[1] = 9.81;		/* WaterTank3\Tank3\gravity */
	xx_P[2] = 1.0;		/* WaterTank3\Tank3\liquid_density */
	xx_P[3] = 7.0;		/* WaterTank3\Valve\resistance */


	/* set the initial values */
	xx_I[0] = 1.0e-4;		/* Drain\drain_volume_initial {m3} */
	xx_I[1] = 0.0;		/* WaterTank3\Tank3\volume_initial */


	/* set the states */
	xx_s[0] = xx_I[0];		/* Drain\drain_volume {m3} */
	xx_s[1] = xx_I[1];		/* WaterTank3\Tank3\volume */


}

/* This function calculates the initial equations of the model.
 * These equations are calculated before anything else
 */
void XXCalculateInitial (void)
{


}

/* This function calculates the static equations of the model.
 * These equations are only dependent from parameters and constants
 */
void XXCalculateStatic (void)
{

}

/* This function calculates the input equations of the model.
 * These equations are dynamic equations that must not change
 * in calls from the integration method (like random and delay).
 */
void XXCalculateInput (void)
{

}

/* This function calculates the dynamic equations of the model.
 * These equations are called from the integration method
 * to calculate the new model rates (that are then integrated).
 */
void XXCalculateDynamic (void)
{
	/* Drain\puddle = 4 * sqrt (abs (Drain\drain_volume) / pi); */
	xx_V[0] = 4.0 * sqrt (XXAbsolute (xx_s[0]) / xx_C[0]);

	/* Time\output = time; */
	xx_V[1] = xx_time;

	/* WaterTank3\Tank3\pipe.e = (WaterTank3\Tank3\gravity * WaterTank3\Tank3\volume) * WaterTank3\Tank3\liquid_density; */
	xx_V[3] = (xx_P[1] * xx_s[1]) * xx_P[2];

	/* WaterTank3\Tank3\level = WaterTank3\Tank3\volume / WaterTank3\Tank3\area; */
	xx_V[2] = xx_s[1] / xx_P[0];

	/* puddle = Drain\puddle; */
	xx_V[6] = xx_V[0];

	/* WaterTank3\inFlow = inFlow; */
	xx_V[4] = xx_V[7];

	/* fmuTime = Time\output; */
	xx_V[9] = xx_V[1];

	/* WaterTank3\valveControl = valveControl; */
	xx_V[5] = xx_V[10];

	/* level = WaterTank3\Tank3\level; */
	xx_V[11] = xx_V[2];

	/* Drain\inFlow = (WaterTank3\Tank3\pipe.e / WaterTank3\Valve\resistance) * WaterTank3\valveControl; */
	xx_R[0] = (xx_V[3] / xx_P[3]) * xx_V[5];

	/* WaterTank3\Tank3\volume_dot = WaterTank3\inFlow - Drain\inFlow; */
	xx_R[1] = xx_V[4] - xx_R[0];


	/* increment the step counter */
	xx_steps++;
}

/* This function calculates the output equations of the model.
 * These equations are not needed for calculation of the rates
 * and are kept separate to make the dynamic set of equations smaller.
 * These dynamic equations are called often more than one time for each
 * integration step that is taken. This makes model computation much faster.
 */
void XXCalculateOutput (void)
{
	/* Tank3OutFlow = Drain\inFlow; */
	xx_V[8] = xx_R[0];

}

/* This function calculates the final equations of the model.
 * These equations are calculated after all the calculations
 * are performed
 */
void XXCalculateFinal (void)
{

}

/* this method is called after all calculations are performed */
void XXModelTerminate(void)
{
}


