/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  src\xxsubmod.h
 *  subm:  WaterTanks2
 *  model: threetank
 *  expmt: threetank
 *  date:  February 4, 2016
 *  time:  4:26:23 PM
 *  user:  INTO-CPS
 *  from:  20-sim 4.6 Professional Single
 *  build: 4.6.1.6733
 **********************************************************/

/* This file describes the model functions
   that are supplied for computation.

   The model itself is the xxmodel.c file
*/

#ifndef XX_SUBMOD_H
#define XX_SUBMOD_H

/* Our own include files */
#include "xxmodel.h"



/* The submodel functions */
void XXInitializeSubmodel (XXDouble t);
void XXCalculateSubmodel (XXDouble t);
void XXTerminateSubmodel (XXDouble t);

#endif

