/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  src\xxmodel.c
 *  model: threetank
 *  expmt: threetank
 *  date:  February 4, 2016
 *  time:  3:14:49 PM
 *  user:  INTO-CPS
 *  from:  20-sim 4.6 Professional Single
 *  build: 4.6.1.6733
 **********************************************************/

/* This file contains the actual model variables and equations */

/* Note: Alias variables are the result of full optimization
   of the model in 20-sim. As a result, only the real variables
   are used in the model for speed. The user may also include
   the alias variables by adding them to the end of the array:

   XXDouble xx_variables[NUMBER_VARIABLES + NUMBER_ALIAS_VARIABLES + 1];
   XXCharacter *xx_variable_names[] = {
     VARIABLE_NAMES, ALIAS_VARIABLE_NAMES, NULL
   };

   and calculate them directly after the output equations:

   void XXCalculateOutput (void)
   {
     OUTPUT_EQUATIONS
     ALIAS_EQUATIONS
   }
*/

/* system include files */
#include <stdlib.h>
#include <math.h>

/* 20-sim include files */
#include "xxmodel.h"
#include "xxfuncs.h"

/* the global variables */
XXDouble xx_start_time = 0.0;
XXDouble xx_finish_time = 20.0;
XXDouble xx_step_size = 0.02;
XXDouble xx_time = 0.0;
XXInteger xx_steps = 0;
XXBoolean xx_initialize = XXTRUE;
XXBoolean xx_major = XXTRUE;
XXBoolean xx_stop_simulation = XXFALSE;

/* the variable arrays */
XXDouble xx_MEMORY[0 + 2 + 0 + 2 + 0 + 0 + 1];
XXDouble* xx_C = xx_MEMORY;		/* constants */
XXDouble* xx_P = xx_MEMORY + 0;			/* parameters */
XXDouble* xx_I = xx_MEMORY + 0 + 2;		/* initial values */
XXDouble* xx_V = xx_MEMORY + 0 + 2 + 0;		/* variables */
XXDouble* xx_s = xx_MEMORY + 0 + 2 + 0 + 2;		/* states */
XXDouble *xx_R = xx_MEMORY + 0 + 2 + 0 + 2 + 0;		/* rates (or new states) */

/* the names of the variables as used in the arrays above
   uncomment this part if these names are needed
XXCharacter *xx_parameter_names[] = {
	"wt3_max",
	"wt3_min"
,	NULL
};
XXCharacter *xx_variable_names[] = {
	"wt3_level",
	"wt3_valve"
,	NULL
};
*/

/* this method is called before calculation is possible */
void XXModelInitialize (void)
{
	/* set the parameters */
	xx_P[0] = 2.0;		/* wt3_max {m} */
	xx_P[1] = 1.0;		/* wt3_min {m} */


}

/* This function calculates the initial equations of the model.
 * These equations are calculated before anything else
 */
void XXCalculateInitial (void)
{

		/* wt3_valve = 0.0; */
		xx_V[1] = 0.0;

}

/* This function calculates the static equations of the model.
 * These equations are only dependent from parameters and constants
 */
void XXCalculateStatic (void)
{

}

/* This function calculates the input equations of the model.
 * These equations are dynamic equations that must not change
 * in calls from the integration method (like random and delay).
 */
void XXCalculateInput (void)
{

}

/* This function calculates the dynamic equations of the model.
 * These equations are called from the integration method
 * to calculate the new model rates (that are then integrated).
 */
void XXCalculateDynamic (void)
{
		/* if (wt3_level >= wt3_max) */
		if (xx_V[0] >= xx_P[0])
		{
			/* wt3_valve = 1.0; */
			xx_V[1] = 1.0;
		}

		/* if (wt3_level < wt3_min) */
		if (xx_V[0] < xx_P[1])
		{
			/* wt3_valve = 0.0; */
			xx_V[1] = 0.0;
		}


	/* increment the step counter */
	xx_steps++;
}

/* This function calculates the output equations of the model.
 * These equations are not needed for calculation of the rates
 * and are kept separate to make the dynamic set of equations smaller.
 * These dynamic equations are called often more than one time for each
 * integration step that is taken. This makes model computation much faster.
 */
void XXCalculateOutput (void)
{

}

/* This function calculates the final equations of the model.
 * These equations are calculated after all the calculations
 * are performed
 */
void XXCalculateFinal (void)
{

}

/* this method is called after all calculations are performed */
void XXModelTerminate(void)
{
}


