/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  src\motionprofiles.h
 *  model: threetankco
 *  expmt: threetankco
 *  date:  November 6, 2015
 *  time:  2:34:26 pm
 *  user:  INTO-CPS
 *  from:  20-sim 4.5 Professional Single
 *  build: 4.5.4.6171
 **********************************************************/

/* This file defines the functions necessary for motion profiles
   functions
*/
