/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  src\xxfuncs.c
 *  model: threetank
 *  expmt: threetank
 *  date:  February 3, 2016
 *  time:  2:33:24 PM
 *  user:  Controllab Internal
 *  from:  Controllab Products B.V., 20-sim 4.7 Professional Single
 *  build: 4.7.1000.6732
 **********************************************************/

/* This file contains support functions for several SIDOPS functions

   For flexibility, ANSI-C is created, and typedefs are used
   for integers and doubles, see the xxfuncs.h file for more
   information on these types.

   This means that all used functions follow the ANSI definition.

   Please check the math.h file of your particular compiler
   to see if this is indeed the case. Otherwise, you might have
   to adapt the used functions below to obtain the same behavior.

*/

/* The system include files */
#include <stdlib.h>
#include <math.h>

/* Our own include files */
#include "xxfuncs.h"

/* Constants that are used in our functions below */

/* The 20-sim SIDOPS functions */
/* 20-sim stubs. Implement them yourself if needed */
XXBoolean XXTimeEvent (XXDouble argument, XXInteger id)
{
#if defined _MSC_VER
#pragma message("warning: The 20-sim 'timeevent' function is not yet implemented in this code generation template")
#elif defined __GNUC__
#warning The 20-sim 'timeevent' function is not yet implemented in this code generation template
#endif
	return 0;
}

XXBoolean XXStopSimulation (XXString message, XXInteger id)
{
	xx_stop_simulation = XXTRUE;
	return 0;
}


