/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  src\xxsubmod.h
 *  subm:  WaterTanks1
 *  model: threetank
 *  expmt: threetank
 *  date:  February 3, 2016
 *  time:  2:33:24 PM
 *  user:  Controllab Internal
 *  from:  Controllab Products B.V., 20-sim 4.7 Professional Single
 *  build: 4.7.1000.6732
 **********************************************************/

/* This file describes the model functions
   that are supplied for computation.

   The model itself is the xxmodel.c file
*/

#ifndef XX_SUBMOD_H
#define XX_SUBMOD_H

/* Our own include files */
#include "xxmodel.h"



/* The submodel functions */
void XXInitializeSubmodel (XXDouble t);
void XXCalculateSubmodel (XXDouble t);
void XXTerminateSubmodel (XXDouble t);

#endif

