/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  src\EulerAngles.h
 *  model: sensorAndTrivialController-02
 *  expmt: sensorAndTrivialController-02
 *  date:  March 29, 2016
 *  time:  10:01:21 AM
 *  user:  INTO-CPS
 *  from:  20-sim 4.6 Professional Single
 *  build: 4.6.0.6684
 **********************************************************/

/*****************************************************************************
--------------------------------------------------------------------------

 Copyright � 1995-2007 Controllab Products B.V. All Rights Reserved.

             www.controllab.nl
               www.20sim.com

 Authors: Frank Groen
--------------------------------------------------------------------------
 Description:

 Contains code for converting between different angle representations
 all 24 different kind of Euler angles
 Quaternions and H-Matrices and Rotation Matrices
--------------------------------------------------------------------------
******************************************************************************/

