/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  src\xxTable2D.h
 *  model: sensorAndTrivialController-02
 *  expmt: sensorAndTrivialController-02
 *  date:  March 29, 2016
 *  time:  10:01:21 AM
 *  user:  INTO-CPS
 *  from:  20-sim 4.6 Professional Single
 *  build: 4.6.0.6684
 **********************************************************/

/* This file defines the functions necessary for table 2D lookup
   functions
*/
/* Empty file; no Table2D support needed for this model */

