/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  src\motionprofiles.c
 *  model: R2G2P_Body_Only
 *  expmt: R2G2P_Body_Only
 *  date:  April 5, 2016
 *  time:  10:29:15 AM
 *  user:  INTO-CPS
 *  from:  20-sim 4.6 Professional Single
 *  build: 4.6.0.6684
 **********************************************************/

/* This file implements the functions necessary for motion profiles
   functions
*/

