/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  src\motionprofiles.c
 *  model: sensorAndTrivialController
 *  expmt: sensorAndTrivialController
 *  date:  March 24, 2016
 *  time:  11:24:12 AM
 *  user:  INTO-CPS
 *  from:  20-sim 4.6 Professional Single
 *  build: 4.6.0.6684
 **********************************************************/

/* This file implements the functions necessary for motion profiles
   functions
*/

